### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by Formasitchijoh**
review todo app project

### CODE REVIEW

**Review by KaptainCS3 — CHANGES_REQUESTED** [review]
Try to void passing too many props 2 level down to a component
adjust props passed to App component from index.js
- move DATA object to App component
- next set this DATA object as initial state in useState of task

**Review by KaptainCS3 — COMMENTED** [review]
Adjust index.js and App.js only

**Review by KaptainCS3 — APPROVED** [review]
Great job your PR will be merge

**Comment by Formasitchijoh** [comment]
> Try to void passing too many props 2 level down to a component adjust props passed to App component from index.js
> 
>     * move DATA object to App component
> 
>     * next set this DATA object as initial state in useState of task

Sorry i haven't had time to check it out but i'll do so

**Review by KaptainCS3 — APPROVED** [review]

**Review by KaptainCS3 — APPROVED** [review]
merge and close PR

**Pull request closed without merging**
